=== Nick-0723/bd1702maven/gather/src/main/resources/configuration.dtd
<!ELEMENT configuration (logger?,gather?,client?,dbStore?,server?,backUP?)>
    <!ELEMENT logger (propertiesFile)>
    <!ATTLIST logger class CDATA #REQUIRED>
        <!ELEMENT propertiesFile (#PCDATA)>

    <!ELEMENT gather (sourceData,canliushujuFile)>
    <!ATTLIST gather class CDATA #REQUIRED>
        <!ELEMENT sourceData (#PCDATA)>
        <!ELEMENT canliushujuFile (#PCDATA)>

    <!ELEMENT client (host,port,tempFile)>
    <!ATTLIST client class CDATA #REQUIRED>
        <!ELEMENT host (#PCDATA)>
        <!ELEMENT port (#PCDATA)>
        <!ELEMENT tempFile (#PCDATA)>

    <!ELEMENT dbStore (#PCDATA)>
    <!ATTLIST dbStore class CDATA #REQUIRED>

    <!ELEMENT server (server_tempFile)>
    <!ATTLIST server class CDATA #REQUIRED>
        <!ELEMENT server_tempFile (#PCDATA)>

    <!ELEMENT backUP (path)>
    <!ATTLIST backUP class CDATA #REQUIRED>
        <!ELEMENT path (#PCDATA)>

=== Nick-0723/bd1702maven/gather/src/main/resources/configuration.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<configuration>
    <logger class="com.briup.logger.WossLogger">
        <propertiesFile>gather/src/main/resources/log4j.properties</propertiesFile>
    </logger>
    <gather class="com.briup.client.WossGather">
        <sourceData>gather/data/radwtmp_test</sourceData>
        <canliushujuFile>canliushuju</canliushujuFile>
    </gather>

    <client class="com.briup.client.WossClient">
        <host>127.0.0.1</host>
        <port>6666</port>
        <tempFile>client.bak</tempFile>
    </client>

    <dbStore class="com.briup.server.WossDBStore"></dbStore>

    <server class="com.briup.server.WossServer">
        <server_tempFile>server.bak</server_tempFile>
    </server>

    <backUp class="com.briup.backup.WossBackUp">
        <path>gather/data/</path>
    </backUp>

</configuration>
